#### Definition of the size of each pool

## TIP1: It can make sense to test small pool sizes for the fast allocator to test corner cases where an allocation would fail

## TIP2: Some programs (such as 'ps') require allocating large memory blocks. Increase the size of the standard pool to handle such cases (for instance, giving a size of 10485760 (10MB))

MEM_POOL_0_SIZE=65536
MEM_POOL_1_SIZE=65536
MEM_POOL_2_SIZE=65536
MEM_POOL_3_SIZE=65536

#### Definition of the allocation policy

## possible values are FF, BF and NF

STDPOOL_POLICY=FF


#### Definition of the memory alignment constraint

MEM_ALIGN_CONSTRAINT=1
